GA_Camera -ph -r 2 -it 
GA_Camera -ph -r 3 -it 
GA_Camera -ph -r 4 -it 
GA_Camera -ph -r 5 -it 
GA_Camera -ph -r 6 -it 
GA_Camera -ph -r 7 -it 
GA_Camera -ph -r 8 -it 
GA_Camera -ph -r 9 -it 

GA_Camera -ph -r 10 -it 
GA_Camera -ph -r 11 -it 
GA_Camera -ph -r 12 -it 
GA_Camera -ph -r 13 -it 
GA_Camera -ph -r 14 -it 
GA_Camera -ph -r 15 -it 
GA_Camera -ph -r 16 -it 
GA_Camera -ph -r 17 -it 
GA_Camera -ph -r 18 -it 
GA_Camera -ph -r 19 -it 

GA_Camera -ph -r 20 -it 
GA_Camera -ph -r 21 -it 
GA_Camera -ph -r 22 -it 
GA_Camera -ph -r 23 -it 
GA_Camera -ph -r 24 -it 
GA_Camera -ph -r 25 -it 
GA_Camera -ph -r 26 -it 
GA_Camera -ph -r 27 -it 
GA_Camera -ph -r 28 -it 
GA_Camera -ph -r 29 -it 
