GA_Camera -r 2 -it -ph
GA_Camera -r 3 -it -ph
GA_Camera -r 4 -it -ph
GA_Camera -r 5 -it -ph
GA_Camera -r 6 -it -ph
GA_Camera -r 7 -it -ph
GA_Camera -r 8 -it -ph
GA_Camera -r 9 -it -ph

GA_Camera -r 10 -it -ph
GA_Camera -r 11 -it -ph
GA_Camera -r 12 -it -ph
GA_Camera -r 13 -it -ph
GA_Camera -r 14 -it -ph
GA_Camera -r 15 -it -ph
GA_Camera -r 16 -it -ph
GA_Camera -r 17 -it -ph
GA_Camera -r 18 -it -ph
GA_Camera -r 19 -it -ph

GA_Camera -r 20 -it -ph
GA_Camera -r 21 -it -ph
GA_Camera -r 22 -it -ph
GA_Camera -r 23 -it -ph
GA_Camera -r 24 -it -ph
GA_Camera -r 25 -it -ph
GA_Camera -r 26 -it -ph
GA_Camera -r 27 -it -ph
GA_Camera -r 28 -it -ph
GA_Camera -r 29 -it -ph