GA_Camera -r 0 -it
GA_Camera -r 1 -it
GA_Camera -r 2 -it
GA_Camera -r 3 -it
GA_Camera -r 4 -it
GA_Camera -r 5 -it
GA_Camera -r 6 -it
GA_Camera -r 7 -it
GA_Camera -r 8 -it
GA_Camera -r 9 -it

GA_Camera -r 10 -it
GA_Camera -r 11 -it
GA_Camera -r 12 -it
GA_Camera -r 13 -it
GA_Camera -r 14 -it
GA_Camera -r 15 -it
GA_Camera -r 16 -it
GA_Camera -r 17 -it
GA_Camera -r 18 -it
GA_Camera -r 19 -it

GA_Camera -r 20 -it
GA_Camera -r 21 -it
GA_Camera -r 22 -it
GA_Camera -r 23 -it
GA_Camera -r 24 -it
GA_Camera -r 25 -it
GA_Camera -r 26 -it
GA_Camera -r 27 -it
GA_Camera -r 28 -it
GA_Camera -r 29 -it